name: Add to Project

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  call:
    uses: control-toolbox/CTActions/.github/workflows/add-to-project.yml@main
    with:
      project-url: "https://github.com/orgs/control-toolbox/projects/5"
    secrets:
      project_token: ${{ secrets.PROJECT_TOKEN }}
